/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: { DEFAULT: '#553DE9', hover: '#4432c4', light: '#E8E4FD' },
        teal: '#1FC5A8',
        pink: '#D63384',
        blue: '#2F71E3',
        ink: '#201515',
        secondary: '#36342E',
        muted: '#939084',
        'muted-accessible': '#6B6960',
        background: '#FFFEFB',
        card: '#FFFFFF',
        hover: '#F8F4F0',
        border: '#ECEAE3',
        'border-light': '#C5C0B1',
        success: '#1FC5A8',
        warning: '#D4A03C',
        danger: '#C45B5B',
        info: '#2F71E3',
        'dark-bg': '#0F0F11',
        'dark-card': '#1A1A1E',
        'dark-border': '#2A2A30',
        'dark-hover': '#222228',
        'dark-ink': '#E8E6E3',
        'dark-muted': '#8A8880',
      },
      fontFamily: {
        heading: ['DM Serif Display', 'Georgia', 'Times New Roman', 'serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ["'JetBrains Mono'", "'Fira Code'", "'Cascadia Code'", 'monospace'],
      },
      borderRadius: {
        btn: '4px',
        card: '5px',
        pill: '9999px',
      },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.06)',
        'card-hover': '0 5px 10px rgba(0,0,0,0.08)',
        button: '0 1px 3px rgba(0,0,0,0.08)',
      },
      fontSize: {
        'display': ['4rem', { lineHeight: '0.95', letterSpacing: '-0.02em' }],
        'h1': ['2.5rem', { lineHeight: '1.0', letterSpacing: '-0.01em' }],
        'h2': ['1.5rem', { lineHeight: '1.3' }],
        'h3': ['1.25rem', { lineHeight: '1.4' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6' }],
        'caption': ['0.875rem', { lineHeight: '1.5' }],
        'small': ['0.75rem', { lineHeight: '1.5', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
